package com.example.tinkoff.presentation.classes

object ReactionsData {

    val reactionsStringList: List<Pair<String, String>> = listOf(
        Pair("grinning", "😀"),
        Pair("smiley", "😃"),
        Pair("big_smile", "😄"),
        Pair("grinning_face_with_smiling_eyes", "😁"),
        Pair("laughing", "😆"),
        Pair("sweat_smile", "😅"),
        Pair("rolling_on_the_floor_laughing", "🤣"),
        Pair("joy", "😂"),
        Pair("smile", "🙂"),
        Pair("upside_down", "🙃"),
        Pair("wink", "😉"),
        Pair("blush", "😊"),
        Pair("innocent", "😇"),
        Pair("heart_eyes", "😍"),
        Pair("heart_kiss", "😘"),
        Pair("kiss", "😗"),
        Pair("smiling_face", "☺"),
        Pair("kiss_with_blush", "😚"),
        Pair("kiss_smiling_eyes", "😙"),
        Pair("yum", "😋"),
        Pair("stuck_out_tongue", "😛"),
        Pair("stuck_out_tongue_wink", "😜"),
        Pair("stuck_out_tongue_closed_eyes", "😝"),
        Pair("money_face", "🤑"),
        Pair("hug", "🤗"),
        Pair("thinking", "🤔"),
        Pair("silence", "🤐"),
        Pair("neutral", "😐"),
        Pair("expressionless", "😑"),
        Pair("speechless", "😶"),
        Pair("smirk", "😏"),
        Pair("unamused", "😒"),
        Pair("rolling_eyes", "🙄"),
        Pair("grimacing", "😬"),
        Pair("sleepy", "😪"),
        Pair("drooling", "🤤"),
        Pair("sleeping", "😴"),
        Pair("lying", "🤥"),
        Pair("relieved", "😌"),
        Pair("mask", "😷"),
        Pair("sick", "🤒"),
        Pair("hurt", "🤕"),
        Pair("nauseated", "🤢"),
        Pair("sneezing", "🤧"),
        Pair("dizzy", "😵"),
        Pair("cowboy", "🤠"),
        Pair("sunglasses", "😎"),
        Pair("clown", "🤡"),
        Pair("goblin", "👺"),
        Pair("poop", "💩"),
        Pair("smiling_devil", "😈"),
        Pair("devil", "👿"),
        Pair("robot", "🤖"),
        Pair("lipstick_kiss", "💋"),
        Pair("heart", "❤"),
        Pair("yellow_heart", "💛"),
        Pair("green_heart", "💚"),
        Pair("blue_heart", "💙"),
        Pair("purple_heart", "💜"),
        Pair("wave", "👋"),
        Pair("stop", "🤚"),
        Pair("high_five", "🖐"),
        Pair("hand", "✋"),
        Pair("ok", "👌"),
        Pair("pensive", "😔")
    )
    val reactionsNameSet: Set<String> = setOf(
        "grinning",
        "smiley",
        "big_smile",
        "grinning_face_with_smiling_eyes",
        "laughing",
        "sweat_smile",
        "rolling_on_the_floor_laughing",
        "joy",
        "smile",
        "upside_down",
        "wink",
        "blush",
        "innocent",
        "heart_eyes",
        "heart_kiss",
        "kiss",
        "smiling_face",
        "kiss_with_blush",
        "kiss_smiling_eyes",
        "yum",
        "stuck_out_tongue",
        "stuck_out_tongue_wink",
        "stuck_out_tongue_closed_eyes",
        "money_face",
        "hug",
        "thinking",
        "silence",
        "neutral",
        "expressionless",
        "speechless",
        "smirk",
        "unamused",
        "rolling_eyes",
        "grimacing",
        "sleepy",
        "drooling",
        "sleeping",
        "lying",
        "relieved",
        "mask",
        "sick",
        "hurt",
        "nauseated",
        "sneezing",
        "dizzy",
        "cowboy",
        "sunglasses",
        "clown",
        "goblin",
        "poop",
        "smiling_devil",
        "devil",
        "robot",
        "lipstick_kiss",
        "heart",
        "yellow_heart",
        "green_heart",
        "blue_heart",
        "purple_heart",
        "wave",
        "stop",
        "high_five",
        "hand",
        "ok",
        "pensive"
    )
}
